services:
  s3:
    image: "zenko/cloudserver:latest-7.10.19"
    container_name: s3
    ports:
      - "8099:80"
    volumes:
      - ./conf/:/usr/src/app/conf/
      - ./config.json:/usr/src/app/config.json
    networks:
      - default

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  imagess3:
    build: ./images
    ports:
      - "8091:8091"
    networks:
      - default

    restart: "on-failure"
    depends_on:
      - s3
      - nginx
  